# Generated by Django 5.1.15 on 2026-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='dipartimento',
            field=models.CharField(blank=True, help_text='Reparto/ufficio (testo libero), da compilare in fase di configurazione.', max_length=120, verbose_name='Dipartimento'),
        ),
    ]
