# Generated by Django 5.1.15 on 2026-06-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_utente_dipartimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='deve_cambiare_password',
            field=models.BooleanField(default=False, help_text="Impostato dall'amministratore dopo un reset della password.", verbose_name='Deve cambiare la password al prossimo accesso'),
        ),
    ]
