# Generated by Django 5.1.15 on 2026-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_utente_deve_cambiare_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('AI_OFFICER', 'Funzione AI'), ('APPROVATORE', 'Approvatore'), ('OWNER', 'Owner di funzione'), ('AUDITOR', 'Auditor (sola lettura)')], default='OWNER', max_length=20, verbose_name='Ruolo nel processo'),
        ),
    ]
