# Generated by Django 5.2.17 on 2026-09-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_utente_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('AI_OFFICER', 'Funzione AI'), ('APP_OFFICER', 'Funzione Applicativa'), ('ITOPS_OFFICER', 'Funzione IT Operations'), ('INFOSEC_OFFICER', 'Funzione Infosec'), ('APPROVATORE', 'Approvatore'), ('OWNER', 'Owner di funzione'), ('AUDITOR', 'Auditor (sola lettura)'), ('LEGALE', 'Funzione Legale'), ('CISO', 'CISO (Sicurezza / NIS2)'), ('DPO', 'DPO (Privacy / GDPR)')], default='OWNER', max_length=20, verbose_name='Ruolo nel processo'),
        ),
    ]
