# Generated by Django 5.1.15 on 2026-06-11 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('funzione', models.CharField(choices=[('RND', 'R&D'), ('IT', 'IT'), ('SALES', 'Sales'), ('SC', 'Supply Chain'), ('FINANCE', 'Finance'), ('HR', 'HR'), ('OPS', 'Operations')], max_length=10, verbose_name='Funzione')),
                ('titolo', models.CharField(max_length=140, verbose_name='Titolo (case study)')),
                ('tipo_soluzione', models.CharField(blank=True, help_text="Es. 'Assistente AI interno', 'Agentiche AI, sviluppo interno'.", max_length=140, verbose_name='Tipo soluzione')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('costo', models.CharField(default='TBD', max_length=80, verbose_name='Costo OPEX/CAPEX')),
                ('saving_economico', models.CharField(default='TBD', max_length=80, verbose_name='Saving economico')),
                ('saving_qualitativo', models.CharField(blank=True, max_length=120, verbose_name='Saving qualitativo')),
                ('saving_efficienza', models.CharField(blank=True, max_length=120, verbose_name='Saving efficienza')),
                ('sal', models.PositiveSmallIntegerField(default=0, verbose_name='SAL %')),
                ('referente_area', models.CharField(blank=True, max_length=120, verbose_name='Referente di area')),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata alla Funzione AI'), ('IN_QUALIFICA', 'In qualifica e analisi'), ('PRESENTATA_COMITATO', 'Presentata al Comitato'), ('IN_DISCUSSIONE', 'In discussione (Comitato)'), ('PRESENTATA_CEO', 'Presentata al CEO'), ('APPROVATA', 'Approvata'), ('RESPINTA', 'Respinta'), ('ATTIVO', 'Progetto attivo'), ('MONITORAGGIO', 'In monitoraggio (SAL)'), ('COMPLETATO', 'Completato')], db_index=True, default='BOZZA', max_length=24)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='richieste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Richiesta',
                'verbose_name_plural': 'Richieste',
                'ordering': ['-creata_il'],
            },
        ),
        migrations.CreateModel(
            name='Transizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(max_length=40)),
                ('etichetta', models.CharField(max_length=120)),
                ('stato_da', models.CharField(max_length=24)),
                ('stato_a', models.CharField(max_length=24)),
                ('nota', models.TextField(blank=True)),
                ('creata_il', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('attore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='azioni', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transizioni', to='flusso.richiesta')),
            ],
            options={
                'verbose_name': 'Evento di workflow',
                'verbose_name_plural': 'Audit trail',
                'ordering': ['creata_il'],
            },
        ),
    ]
