# Generated by Django 5.1.15 on 2026-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='altri_costi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altri costi (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='altri_costi_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dettaglio altri costi'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='analisi_fattibilita',
            field=models.TextField(blank=True, verbose_name='Analisi di fattibilità'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_token_ai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costi token AI (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='data_consegna_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista consegna'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='data_inizio',
            field=models.DateField(blank=True, null=True, verbose_name='Data inizio lavori'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='effort_ore',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Effort stimato (ore)'),
        ),
    ]
