# Generated by Django 5.1.15 on 2026-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0002_richiesta_altri_costi_richiesta_altri_costi_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata alla Funzione AI'), ('IN_QUALIFICA', 'In qualifica e analisi'), ('IN_APPROVAZIONE', 'In approvazione'), ('APPROVATA', 'Approvata'), ('RESPINTA', 'Respinta'), ('ATTIVO', 'Progetto attivo'), ('MONITORAGGIO', 'In monitoraggio (SAL)'), ('COMPLETATO', 'Completato')], db_index=True, default='BOZZA', max_length=24),
        ),
    ]
