# Generated by Django 5.1.15 on 2026-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0003_alter_richiesta_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilitato', models.BooleanField(default=False, verbose_name='Analisi AI abilitata')),
                ('api_key', models.CharField(blank=True, help_text="In alternativa impostare la variabile d'ambiente ANTHROPIC_API_KEY, che ha la precedenza ed evita di salvare la chiave nel database.", max_length=200, verbose_name='API key Anthropic')),
                ('modello', models.CharField(choices=[('claude-sonnet-4-6', 'Claude Sonnet 4.6 — consigliato (qualità/costo)'), ('claude-opus-4-8', 'Claude Opus 4.8 — massima qualità'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 — rapido ed economico'), ('claude-fable-5', 'Claude Fable 5')], default='claude-sonnet-4-6', max_length=60, verbose_name='Modello')),
                ('max_tokens', models.PositiveIntegerField(default=1200, verbose_name='Lunghezza massima risposta (token)')),
                ('includi_titoli', models.BooleanField(default=False, help_text="Se disattivo, all'AI vengono inviati solo numeri aggregati (nessun titolo).", verbose_name='Includi i titoli dei progetti attivi nel prompt')),
                ('prompt_sistema', models.TextField(blank=True, help_text='Lascia vuoto per usare le istruzioni predefinite.', verbose_name='Istruzioni di sistema')),
                ('ultima_analisi', models.TextField(blank=True, verbose_name='Ultima analisi generata')),
                ('ultima_analisi_il', models.DateTimeField(blank=True, null=True)),
                ('ultimo_modello', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Configurazione AI',
                'verbose_name_plural': 'Configurazione AI',
            },
        ),
    ]
