# Generated by Django 5.2.15 on 2026-06-19 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0006_notifiche_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneai',
            name='prompt_rischio',
            field=models.TextField(blank=True, help_text='Lascia vuoto per usare le istruzioni predefinite.', verbose_name='Istruzioni di classificazione del rischio'),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='rischio_bulk_avviato_il',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='rischio_bulk_fatti',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='rischio_bulk_in_corso',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='rischio_bulk_totale',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio',
            field=models.CharField(blank=True, choices=[('VIETATO', 'Inaccettabile / Vietato (art. 5)'), ('ALTO', 'Alto rischio (Allegato III / I)'), ('LIMITATO', 'Rischio limitato — trasparenza (art. 50)'), ('MINIMO', 'Rischio minimo')], help_text='Classificazione effettiva (vuota finché non analizzata).', max_length=12, verbose_name='Rischio AI Act'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_ai_categoria',
            field=models.CharField(blank=True, choices=[('VIETATO', 'Inaccettabile / Vietato (art. 5)'), ('ALTO', 'Alto rischio (Allegato III / I)'), ('LIMITATO', 'Rischio limitato — trasparenza (art. 50)'), ('MINIMO', 'Rischio minimo')], max_length=12),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_ai_il',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analisi AI del'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_ai_modello',
            field=models.CharField(blank=True, max_length=60, verbose_name='Modello AI usato'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_motivazione',
            field=models.TextField(blank=True, verbose_name='Motivazione del rischio'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_nota_legale',
            field=models.TextField(blank=True, verbose_name='Nota della Funzione Legale'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_obblighi',
            field=models.TextField(blank=True, verbose_name='Obblighi derivati'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_riferimenti',
            field=models.CharField(blank=True, max_length=300, verbose_name='Riferimenti normativi'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_stato',
            field=models.CharField(choices=[('DA_ANALIZZARE', 'Da analizzare'), ('PROPOSTO_AI', "Proposto dall'AI — da validare"), ('VALIDATO', 'Validato dalla Funzione Legale'), ('MODIFICATO', 'Modificato dalla Funzione Legale')], db_index=True, default='DA_ANALIZZARE', max_length=16, verbose_name='Stato classificazione'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_validato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rischi_validati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='rischio_validato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
