# Generated by Django 5.2.15 on 2026-06-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0007_configurazioneai_prompt_rischio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurazioneai',
            name='prompt_rischio',
        ),
        migrations.RemoveField(
            model_name='configurazioneai',
            name='rischio_bulk_avviato_il',
        ),
        migrations.RemoveField(
            model_name='configurazioneai',
            name='rischio_bulk_fatti',
        ),
        migrations.RemoveField(
            model_name='configurazioneai',
            name='rischio_bulk_in_corso',
        ),
        migrations.RemoveField(
            model_name='configurazioneai',
            name='rischio_bulk_totale',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_ai_categoria',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_ai_il',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_ai_modello',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_motivazione',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_nota_legale',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_obblighi',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_riferimenti',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_stato',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_validato_da',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='rischio_validato_il',
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='prompt_rischio_aiact',
            field=models.TextField(blank=True, help_text='Lascia vuoto per usare le istruzioni predefinite.', verbose_name='Istruzioni classificazione AI Act'),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='prompt_rischio_gdpr',
            field=models.TextField(blank=True, help_text='Lascia vuoto per usare le istruzioni predefinite.', verbose_name='Istruzioni classificazione GDPR'),
        ),
        migrations.AddField(
            model_name='configurazioneai',
            name='prompt_rischio_nis2',
            field=models.TextField(blank=True, help_text='Lascia vuoto per usare le istruzioni predefinite.', verbose_name='Istruzioni classificazione NIS2'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='incrementi_ai_stimati',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='incremento_efficienza_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note incremento efficienza'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='incremento_qualitativo_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note incremento qualitativo'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='saving_economico_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note saving economico'),
        ),
        migrations.CreateModel(
            name='ClassificazioneRischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AIACT', 'AI Act'), ('NIS2', 'NIS2'), ('GDPR', 'GDPR')], db_index=True, max_length=6)),
                ('categoria', models.CharField(blank=True, max_length=12)),
                ('stato', models.CharField(choices=[('DA_ANALIZZARE', 'Da analizzare'), ('PROPOSTO_AI', "Proposto dall'AI — da validare"), ('VALIDATO', 'Validato dal presidio'), ('MODIFICATO', 'Modificato dal presidio')], db_index=True, default='DA_ANALIZZARE', max_length=16)),
                ('motivazione', models.TextField(blank=True)),
                ('riferimenti', models.CharField(blank=True, max_length=300)),
                ('obblighi', models.TextField(blank=True)),
                ('ai_categoria', models.CharField(blank=True, max_length=12)),
                ('ai_il', models.DateTimeField(blank=True, null=True)),
                ('ai_modello', models.CharField(blank=True, max_length=60)),
                ('validato_il', models.DateTimeField(blank=True, null=True)),
                ('nota_validatore', models.TextField(blank=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificazioni', to='flusso.richiesta')),
                ('validato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rischi_validati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classificazione di rischio',
                'verbose_name_plural': 'Classificazioni di rischio',
                'ordering': ['richiesta', 'tipo'],
                'unique_together': {('richiesta', 'tipo')},
            },
        ),
    ]
