# Generated by Django 5.2.15 on 2026-06-19 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0008_remove_configurazioneai_prompt_rischio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classificazionerischio',
            name='residuo_convalidato',
            field=models.BooleanField(default=False, verbose_name='Rischio residuo convalidato dal presidio'),
        ),
        migrations.AddField(
            model_name='classificazionerischio',
            name='rischio_residuo',
            field=models.CharField(blank=True, help_text='Livello atteso dopo il trattamento. Vuoto = pari al rischio inerente.', max_length=12, verbose_name='Rischio residuo'),
        ),
        migrations.AddField(
            model_name='classificazionerischio',
            name='strategia',
            field=models.CharField(choices=[('ACCETTATO', 'Accettato'), ('MITIGATO', 'Mitigato (ridotto)'), ('TRASFERITO', 'Trasferito'), ('EVITATO', 'Evitato (eliminato)')], default='ACCETTATO', max_length=12, verbose_name='Strategia di trattamento'),
        ),
        migrations.AddField(
            model_name='classificazionerischio',
            name='trattamento_note',
            field=models.TextField(blank=True, help_text="Per il trasferimento: a chi/come. Per l'accettazione: motivazione.", verbose_name='Note di trattamento'),
        ),
        migrations.AddField(
            model_name='classificazionerischio',
            name='trattato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rischi_trattati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classificazionerischio',
            name='trattato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AzioneTrattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500, verbose_name='Azione da intraprendere')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data prevista di applicazione')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('creata_il', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classificazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni', to='flusso.classificazionerischio')),
            ],
            options={
                'verbose_name': 'Azione di trattamento',
                'verbose_name_plural': 'Azioni di trattamento',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
