# Generated by Django 5.2.15 on 2026-06-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0009_classificazionerischio_residuo_convalidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='ai_autonomia',
            field=models.CharField(blank=True, choices=[('NON_AGENTICA', 'Non agentica'), ('AGENTICA_SUPPORTO', "Agentica — a supporto dell'utente (human-in-the-loop)"), ('AGENTICA_AUTONOMA', 'Agentica — autonoma')], help_text='Grado di autonomia: non agentica, agentica a supporto, agentica autonoma.', max_length=20, verbose_name='Tipo di AI'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ai_deployment',
            field=models.CharField(blank=True, choices=[('API', 'API (cloud)'), ('LOCALE', 'LLM locale (on-premise)'), ('IBRIDO', 'Ibrido (API + locale)')], help_text='API (cloud), LLM locale (on-premise) o ibrido. Impatta GDPR/NIS2.', max_length=10, verbose_name='Infrastruttura prevista'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_token_ambito',
            field=models.CharField(blank=True, choices=[('UTENTE', 'Per utente'), ('TEAM', 'Per team'), ('COMPLESSIVO', 'Complessivo')], max_length=12, verbose_name='Ambito costo token'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_token_periodicita',
            field=models.CharField(blank=True, choices=[('MENSILE', 'Mensile'), ('ANNUALE', 'Annuale'), ('UNA_TANTUM', 'Una tantum')], max_length=12, verbose_name='Periodicità costo token'),
        ),
    ]
