# Generated by Django 5.2.15 on 2026-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0010_richiesta_ai_autonomia_richiesta_ai_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='costo_token_ai_stimato',
            field=models.BooleanField(default=False, editable=False, help_text="True se l'importo token è stato proposto dall'AI (modificabile)."),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='numero_utenti',
            field=models.PositiveIntegerField(blank=True, help_text='Numero di utenti (o di team) su cui scalare il costo per ottenere il totale.', null=True, verbose_name='Numero utenti/team'),
        ),
    ]
