# Generated by Django 5.2.15 on 2026-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0011_richiesta_costo_token_ai_stimato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='budget_massimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importo massimo a budget per il progetto.', max_digits=12, null=True, verbose_name='Budget massimo disponibile (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='extra_budget_massimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Importo massimo extra budget che l'owner è disposto a richiedere.", max_digits=12, null=True, verbose_name='Extra budget richiedibile (€)'),
        ),
    ]
