# Generated by Django 5.2.15 on 2026-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0012_richiesta_budget_massimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='esito_budget',
            field=models.CharField(blank=True, choices=[('A_BUDGET', 'A budget'), ('EXTRA_BUDGET', 'Extra budget')], help_text="Decisione dell'owner sull'importo stimato: a budget o extra budget.", max_length=12, verbose_name='Esito budget'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='saving_economico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Beneficio economico atteso (€)'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='saving_economico_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note beneficio economico'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata alla Funzione AI'), ('IN_QUALIFICA', 'In qualifica e analisi'), ('ATTESA_BUDGET', 'Attesa decisione budget (owner)'), ('IN_APPROVAZIONE', 'In approvazione'), ('APPROVATA', 'Approvata'), ('RESPINTA', 'Respinta'), ('ARCHIVIATA', "Archiviata dall'owner"), ('ATTIVO', 'Progetto attivo'), ('MONITORAGGIO', 'In monitoraggio (SAL)'), ('COMPLETATO', 'Completato')], db_index=True, default='BOZZA', max_length=24),
        ),
    ]
