# Generated by Django 5.2.15 on 2026-07-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0013_richiesta_esito_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata alla Funzione AI'), ('IN_QUALIFICA', 'In qualifica e analisi'), ('ATTESA_BUDGET', 'Attesa decisione budget (owner)'), ('PRONTA_APPROVAZIONE', 'Pronta per approvazione'), ('IN_APPROVAZIONE', 'In approvazione'), ('APPROVATA', 'Approvata'), ('RESPINTA', 'Respinta'), ('ARCHIVIATA', "Archiviata dall'owner"), ('ATTIVO', 'Progetto attivo'), ('MONITORAGGIO', 'In monitoraggio (SAL)'), ('COMPLETATO', 'Completato')], db_index=True, default='BOZZA', max_length=24),
        ),
    ]
