# Generated by Django 5.2.16 on 2026-07-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0014_alter_richiesta_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceEffort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivita', models.CharField(choices=[('ANALISI', 'Analisi e progettazione'), ('SVILUPPO', 'Sviluppo'), ('TEST', 'Test e validazione'), ('COMPLIANCE', 'Compliance e rischio'), ('INFRASTRUTTURA', 'Infrastruttura e deploy'), ('ADOZIONE', 'Formazione e adozione')], max_length=16)),
                ('figura', models.CharField(choices=[('FUNZIONE_AI', 'Funzione AI'), ('OWNER', 'Owner / delegati'), ('INFRA', 'IT / Infrastruttura'), ('PRESIDI', 'Presìdi (CISO/DPO/Legale)'), ('UTENTI', 'Utenti chiave')], max_length=16)),
                ('ore', models.PositiveIntegerField(default=0)),
                ('stimata_ai', models.BooleanField(default=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_effort', to='flusso.richiesta')),
            ],
            options={
                'verbose_name': 'Voce effort',
                'verbose_name_plural': 'Voci effort',
            },
        ),
    ]
