# Generated by Django 5.2.17 on 2026-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0015_voceeffort'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='tipo',
            field=models.CharField(choices=[('AI', 'AI — Intelligenza Artificiale (registro AI Act)'), ('APPLICATION', 'Application — nuovi software, implementazioni ERP…'), ('IT_OPERATION', 'IT Operation')], db_index=True, default='AI', help_text='AI (perimetro registro AI Act), Application (software/ERP) o IT Operation.', max_length=16, verbose_name='Tipo di richiesta'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata alla Funzione tecnica'), ('IN_QUALIFICA', 'In qualifica e analisi'), ('ATTESA_BUDGET', 'Attesa decisione budget (owner)'), ('PRONTA_APPROVAZIONE', 'Pronta per approvazione'), ('IN_APPROVAZIONE', 'In approvazione'), ('APPROVATA', 'Approvata'), ('RESPINTA', 'Respinta'), ('ARCHIVIATA', "Archiviata dall'owner"), ('ATTIVO', 'Progetto attivo'), ('MONITORAGGIO', 'In monitoraggio (SAL)'), ('COMPLETATO', 'Completato')], db_index=True, default='BOZZA', max_length=24),
        ),
        migrations.AlterField(
            model_name='voceeffort',
            name='figura',
            field=models.CharField(choices=[('FUNZIONE_AI', 'Funzione tecnica'), ('OWNER', 'Owner / delegati'), ('INFRA', 'IT / Infrastruttura'), ('PRESIDI', 'Presìdi (CISO/DPO/Legale)'), ('UTENTI', 'Utenti chiave')], max_length=16),
        ),
    ]
