# Generated by Django 5.2.17 on 2026-09-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0016_richiesta_tipo_alter_richiesta_stato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='budget_it',
            field=models.CharField(blank=True, choices=[('BUDGET', 'Budget'), ('EXTRA_BUDGET', 'Extra Budget')], help_text='Copertura sul budget IT: a budget o extra budget.', max_length=16, verbose_name='Budget IT'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='clone_di',
            field=models.ForeignKey(blank=True, editable=False, help_text='Scheda AI di origine, se questa è una scheda clonata.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloni', to='flusso.richiesta'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='dettaglio_application',
            field=models.TextField(blank=True, help_text='Componente applicativa (nuovi software, ERP…). Se compilato genera una scheda dedicata per la Funzione Applicativa.', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='dettaglio_it_operation',
            field=models.TextField(blank=True, help_text='Componente IT Operation. Se compilato genera una scheda dedicata per la Funzione IT Operations.', verbose_name='IT Operation'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='entity',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('ROMANIA', 'Romania'), ('SPAGNA', 'Spagna'), ('FRANCIA', 'Francia'), ('GERMANIA', 'Germania'), ('EXTRA_UE', 'Extra UE'), ('ALL', 'All')], help_text="Entità di riferimento; se indicata dall'owner viene riportata nell'analisi.", max_length=12, verbose_name='Entity'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='is_capex',
            field=models.BooleanField(default=False, verbose_name='Capex'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='is_ifrs',
            field=models.BooleanField(default=False, verbose_name='IFRS'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='is_opex',
            field=models.BooleanField(default=False, verbose_name='Opex'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='priorita',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BASSA', 'Bassa')], db_index=True, default='MEDIA', help_text="Priorità attribuita dall'owner.", max_length=8, verbose_name='Priorità'),
        ),
    ]
