# Generated by Django 5.2.17 on 2026-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0017_richiesta_budget_it_richiesta_clone_di_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='costo_owner',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Costi sul budget dell'owner: consulenti esterni, servizi, licenze già a suo carico.", max_digits=12, null=True, verbose_name="Costo a carico dell'owner (€)"),
        ),
    ]
