# Generated by Django 5.2.17 on 2026-09-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0018_richiesta_costo_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoglioBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.SlugField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('BUDGET', 'Budget'), ('EXTRA', 'Extra Budget'), ('SUPPORTO', 'Foglio di supporto')], default='SUPPORTO', max_length=12)),
                ('anno', models.PositiveIntegerField(default=2026)),
                ('intestazioni', models.JSONField(default=list)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foglio budget',
                'verbose_name_plural': 'Fogli budget',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RigaBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(db_index=True, default=0)),
                ('dati', models.JSONField(default=list)),
                ('da_progetto', models.BooleanField(default=False)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('foglio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='flusso.fogliobudget')),
                ('richiesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righe_budget', to='flusso.richiesta')),
            ],
            options={
                'verbose_name': 'Riga budget',
                'verbose_name_plural': 'Righe budget',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
