# Generated by Django 5.2.17 on 2026-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0019_fogliobudget_rigabudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='app_capex',
            field=models.BooleanField(default=False, verbose_name='Capex (Application)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='app_ifrs',
            field=models.BooleanField(default=False, verbose_name='IFRS (Application)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='app_opex',
            field=models.BooleanField(default=False, verbose_name='Opex (Application)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ops_capex',
            field=models.BooleanField(default=False, verbose_name='Capex (IT Operation)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ops_ifrs',
            field=models.BooleanField(default=False, verbose_name='IFRS (IT Operation)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ops_opex',
            field=models.BooleanField(default=False, verbose_name='Opex (IT Operation)'),
        ),
    ]
