# Generated by Django 5.2.17 on 2026-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0020_richiesta_app_capex_richiesta_app_ifrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='costo_application',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo della componente applicativa: viene riportato sulla scheda generata.', max_digits=12, null=True, verbose_name='Costo componente Application (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_it_operation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo della componente IT Operation: viene riportato sulla scheda generata.', max_digits=12, null=True, verbose_name='Costo componente IT Operation (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='data_necessita',
            field=models.DateField(blank=True, help_text="Data entro cui l'owner ha bisogno della soluzione: guida la pianificazione.", null=True, verbose_name='Entro quando serve'),
        ),
    ]
