# Generated by Django 5.2.17 on 2026-09-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0021_richiesta_costo_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='tipo',
            field=models.CharField(choices=[('AI', 'AI — Intelligenza Artificiale (registro AI Act)'), ('APPLICATION', 'Application — nuovi software, implementazioni ERP…'), ('IT_OPERATION', 'IT Operation'), ('INFOSEC', 'Infosec — sicurezza informatica')], db_index=True, default='AI', help_text='AI (perimetro registro AI Act), Application (software/ERP) o IT Operation.', max_length=16, verbose_name='Tipo di richiesta'),
        ),
    ]
