# Generated by Django 5.2.17 on 2026-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0022_alter_richiesta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='priorita_it',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BASSA', 'Bassa')], help_text="Priorità attribuita in analisi dalla funzione tecnica; si affianca a quella dell'owner, non la sostituisce.", max_length=8, verbose_name='Priorità IT'),
        ),
    ]
