# Generated by Django 5.2.17 on 2026-09-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0023_richiesta_priorita_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='natura',
            field=models.CharField(choices=[('PROGETTO', 'Progetto'), ('ATTIVITA', 'Attività')], db_index=True, default='PROGETTO', help_text='Le attività finiscono nel budget con la sigla «A» ma restano fuori da schedulazione, KPI, costi ed effort.', max_length=9, verbose_name='Progetto o attività'),
        ),
    ]
