# Generated by Django 5.2.17 on 2026-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0024_richiesta_natura'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='ai_capex',
            field=models.BooleanField(default=False, verbose_name='Capex (AI)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ai_ifrs',
            field=models.BooleanField(default=False, verbose_name='IFRS (AI)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='ai_opex',
            field=models.BooleanField(default=False, verbose_name='Opex (AI)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_ai',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo della sola componente AI: diventa il costo della scheda generata.', max_digits=12, null=True, verbose_name='Costo AI (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='dettaglio_ai',
            field=models.TextField(blank=True, help_text="Parte del progetto che usa l'AI: se compilata genera una scheda per la Funzione AI.", verbose_name='Componente AI'),
        ),
    ]
