# Generated by Django 5.2.17 on 2026-09-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0025_richiesta_ai_capex_richiesta_ai_ifrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigabudget',
            name='richiesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='righe_budget', to='flusso.richiesta'),
        ),
    ]
