# Generated by Django 5.2.17 on 2026-09-22 12:12

from django.db import migrations, models


def hd_diventa_hq(apps, schema_editor):
    """I progetti esistenti con entity «HD» passano a «HQ» (era un refuso)."""
    apps.get_model("flusso", "Richiesta").objects.filter(entity="HD").update(entity="HQ")


def hq_torna_hd(apps, schema_editor):
    apps.get_model("flusso", "Richiesta").objects.filter(entity="HQ").update(entity="HD")


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0026_alter_rigabudget_richiesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiesta',
            name='entity',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('ROMANIA', 'Romania'), ('SPAGNA', 'Spagna'), ('FRANCIA', 'Francia'), ('GERMANIA', 'Germania'), ('EXTRA_UE', 'Extra UE'), ('ALL', 'All')], help_text="Entità di riferimento; se indicata dall'owner viene riportata nell'analisi.", max_length=12, verbose_name='Entity'),
        ),
        migrations.RunPython(hd_diventa_hq, hq_torna_hd),
    ]
