# Generated by Django 5.2.17 on 2026-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flusso', '0027_entity_hq'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='costo_capex',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Parte dell'importo da capitalizzare; si compila quando il progetto è insieme capex e opex.", max_digits=12, null=True, verbose_name='Quota Capex (€)'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='costo_opex',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Parte dell'importo a conto economico; si compila quando il progetto è insieme capex e opex.", max_digits=12, null=True, verbose_name='Quota Opex (€)'),
        ),
    ]
